'use strict';

var https = require('https');
var fs = require('fs');

/* Server specific version of Zone.js */
require('zone.js/dist/zone-node');

const express = require('express');
const ngUniversal = require('@nguniversal/express-engine');

/* The server bundle is loaded here, it's why you don't want a changing hash in it */
const { AppServerModuleNgFactory } = require('./dev-server/main.js');

/* Server-side rendering */
function angularRouter(req, res) {
  /* Server-side rendering */
  res.render('index', { req, res });
}

const app = express();

/* Root route before static files, or it will serve a static index.html, without pre-rendering */
app.get('/', angularRouter);

app.get("/exit", function(req, res) {
  console.log("exiting node from server");
  process.exit(1);
});

/* Serve the static files generated by the CLI (index.html, CSS? JS, assets...) */
app.use(express.static(`${__dirname}/dev-dist`));

/* Configure Angular Express engine */
app.engine('html', ngUniversal.ngExpressEngine({
  bootstrap: AppServerModuleNgFactory
}));
app.set('view engine', 'html');
app.set('views', 'dev-dist');

/* Direct all routes to index.html, where Angular will take care of routing */
app.get('*', angularRouter);

var port = 8080;

var pkey = fs.readFileSync('key.pem').toString();
var pcert = fs.readFileSync('cert.pem').toString();

var options = {
    key: pkey,
    cert: pcert,
};

https.createServer(options, app).listen(port);
console.log('Node server start on port: ' + port);
